import type { DeckDefinition } from './types';

/**
 * Structure Deck: The Crimson King (SDCK), TCG 2023.
 * 49 cards (SDCK-EN001..SDCK-EN049, one copy each): 40 Main Deck + 9 Extra Deck.
 * Konami's official card count equals the number of distinct set numbers, so every card is a single copy.
 */
export const THE_CRIMSON_KING: DeckDefinition = {
  id: 'sdck',
  name: 'The Crimson King',
  description: 'Structure Deck (2023). Resonators and Red Dragon Archfiend Synchro Monsters, up to Red Nova Dragon and King Calamity.',
  main: [
    { name: 'Soul Resonator', qty: 1 },
    { name: 'Vision Resonator', qty: 1 },
    { name: 'Bone Archfiend', qty: 1 },
    { name: 'Dark Resonator', qty: 1 },
    { name: 'Creation Resonator', qty: 1 },
    { name: 'Synkron Resonator', qty: 1 },
    { name: 'Red Resonator', qty: 1 },
    { name: 'Crimson Resonator', qty: 1 },
    { name: 'Vice Dragon', qty: 1 },
    { name: 'Battle Fader', qty: 1 },
    { name: 'Red Sprinter', qty: 1 },
    { name: 'Red Warg', qty: 1 },
    { name: 'Wandering King Wildwind', qty: 1 },
    { name: 'Phantom King Hydride', qty: 1 },
    { name: 'Magical King Moonstar', qty: 1 },
    { name: 'Absolute King Back Jack', qty: 1 },
    { name: 'Red Dragon Archfiend/Assault Mode', qty: 1 },
    { name: 'Assault Beast', qty: 1 },
    { name: 'Psi-Reflector', qty: 1 },
    { name: 'Fire Ant Ascator', qty: 1 },
    { name: 'Ascator, Dawnwalker', qty: 1 },
    { name: 'Danger! Nessie!', qty: 1 },
    { name: 'Danger! Chupacabra!', qty: 1 },
    { name: 'Witch of the Black Forest', qty: 1 },
    { name: 'Absolute Powerforce', qty: 1 },
    { name: 'Crimson Gaia', qty: 1 },
    { name: 'Resonator Engine', qty: 1 },
    { name: 'Resonator Call', qty: 1 },
    { name: 'Resonator Command', qty: 1 },
    { name: 'Burning Soul', qty: 1 },
    { name: 'Pot of Extravagance', qty: 1 },
    { name: 'Fiendish Golem', qty: 1 },
    { name: 'Red Zone', qty: 1 },
    { name: 'King\'s Synchro', qty: 1 },
    { name: 'Red Reign', qty: 1 },
    { name: 'Time to Stand Up', qty: 1 },
    { name: 'Fiendish Chain', qty: 1 },
    { name: 'Powerful Rebirth', qty: 1 },
    { name: 'Assault Mode Activate', qty: 1 },
    { name: 'Terrors of the Overroot', qty: 1 },
  ],
  extra: [
    { name: 'Scarlight Red Dragon Archfiend', qty: 1 },
    { name: 'Hot Red Dragon Archfiend Abyss', qty: 1 },
    { name: 'Hot Red Dragon Archfiend Bane', qty: 1 },
    { name: 'Red Supernova Dragon', qty: 1 },
    { name: 'Red Dragon Archfiend', qty: 1 },
    { name: 'Red Nova Dragon', qty: 1 },
    { name: 'Hot Red Dragon Archfiend King Calamity', qty: 1 },
    { name: 'Red Rising Dragon', qty: 1 },
    { name: 'Scarred Dragon Archfiend', qty: 1 },
  ],
};
